version: '3'
services:
 postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: domain
    ports:
      - "5432:5432"
    networks:
      - ch_network
 redis:
    image: redis:latest
    restart: always
    command: redis-server --loglevel notice --requirepass pass
    ports:
      - "6379:6379"
    volumes: 
      - cache:/data
    networks:
      - ch_network
 clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "9000:9000"
    restart: always
    networks:
      - ch_network
 nats:
    image: nats:latest
    restart: always
    ports:
      - "4222:4222"
    networks:
      - ch_network
 service-1:
    build: ./service-1/.
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - nats
    networks:
      - ch_network
 service-2:
    build: ./service-2/.
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - clickhouse
      - nats
    networks:
      - ch_network

networks:
 ch_network:
    driver: bridge

volumes:
  cache:
    driver: local
